//+------------------------------------------------------------------+
//|                                                      CloseAll.mq5|
//|                        Generated by AI                          |
//+------------------------------------------------------------------+
#property copyright ""
#property link ""
#property version "1.00"
#property strict

#include <Trade/Trade.mqh>

input int CheckIntervalMs = 500; // Timer interval in milliseconds
input int CloseHour = 5;
input int CloseMinute = 0;
input int CloseSecond = 58;

CTrade trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    EventSetTimer(CheckIntervalMs / 1000.0); // Set timer in seconds
    return (INIT_SUCCEEDED);
}
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    EventKillTimer();
}
//+------------------------------------------------------------------+
//| Timer function                                                   |
//+------------------------------------------------------------------+
void OnTimer()
{
    // Adjust server time to GMT+7 (add 7 hours = 25200 seconds)
    datetime now_gmt7 = TimeCurrent() + 25200;
    MqlDateTime tm;
    TimeToStruct(now_gmt7, tm);
    if ((tm.hour > CloseHour) ||
        (tm.hour == CloseHour && tm.min > CloseMinute) ||
        (tm.hour == CloseHour && tm.min == CloseMinute && tm.sec >= CloseSecond))
    {
        CloseAllPositions();
    }
}
//+------------------------------------------------------------------+
//| Function to close all open positions                             |
//+------------------------------------------------------------------+
void CloseAllPositions()
{
    int total = PositionsTotal();
    for (int i = total - 1; i >= 0; i--)
    {
        ulong ticket = PositionGetTicket(i);
        if (PositionSelectByTicket(ticket))
        {
            string symbol = PositionGetString(POSITION_SYMBOL);
            if (!trade.PositionClose(symbol))
            {
                Print("Failed to close position for ", symbol, ": ", GetLastError());
            }
        }
    }
}
//+------------------------------------------------------------------+